repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910-1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint
        language: system
        types: [python]
